#!/bin/sh
#
# slurp - this script starts and stops the slurp daemon
#
# chkconfig: - 85 15
# description: slurp
# processname: slurp
# config: /etc/sysconfig/slurp
# pidfile: /var/run/slurp.pid
# lockfile: /var/lock/subsys/slurp

# source function library.
. /etc/rc.d/init.d/functions

# source networking configuration.
. /etc/sysconfig/network

# check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

NAME=slurp
USER=root
PROG="slurp"
PID_FILE="/var/run/slurp.pid"
LOCK_FILE="/var/lock/subsys/slurp"
CONFIG="/etc/sysconfig/slurp"
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

MONITOR_PATHS="/var/log/messages"
STATE_PATH="/var/lib/slurp"
CONSUMERS="/etc/slurp.d"
LOG_LEVEL="info"

if [ -f $CONFIG ]; then
    . $CONFIG
fi

OPTS="monitor \
$MONITOR_PATHS \
--state-path=$STATE_PATH \
--consumer=$CONSUMERS \
--log-level=$LOG_LEVEL \
--daemonize --pid-file=$PID_FILE \
--enable-syslog"

start() {
    [ -x $PROG ] || exit 5
    echo -n $"Starting $NAME: "
    if [ "$(id -u)" != "0" ]; then
daemon --pidfile $PIDFILE $PROG $OPTS
    else
daemon --pidfile $PIDFILE --user $USER $PROG $OPTS
    fi
retval=$?
    echo
    [ $retval -eq 0 ] && touch $LOCKFILE
    return $retval
}

stop() {
    echo -n $"Stopping $NAME: "
    killproc -p $PIDFILE $NAME
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $LOCKFILE
    return $retval
}

restart() {
    stop
    start
}

reload() {
    echo -n $"Reloading $NAME: "
    killproc -p $PIDFILE $NAME -HUP
    echo
}

force_reload() {
    restart
}

rh_status() {
    status -p $PIDFILE $NAME
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    cond-restart|try-restart)
        rh_status_q || exit 0
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|cond-restart|try-restart|force-reload}"
        exit 2
esac
