---
driver:
  name: ec2
  region: us-west-1
  availability_zone: us-west-1a
  ssh_key: <%= ENV['AWS_KEYFILE'] %>

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
    - recipe[balanced-apt]
    - recipe[slurp_test]    
    attributes:
      citadel:
        access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
      balanced-apt:
        allow_unstable: true
